name: aerosol_demo
channels:
  - conda-forge
  - anaconda
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - anaconda=custom=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.6
  - ca-certificates=2019.6.16
  - cairo=1.14.12
  - certifi=2019.6.16=py37_0
  - cftime=1.0.3.4
  - curl=7.64.1
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - harfbuzz
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - jpeg=9b
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - krb5=1.16.1
  - libcurl=7.64.1
  - libcxx
  - libffi=3.2.1
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - make=4.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - netcdf4=1.4.2
  - notebook=5.7.8=py37_0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1c
  - pandas=0.24.2
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - pcre=8.43
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.1.1=py37_0
  - pixman=0.38.0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0
  - pygments=2.4.2=py_0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtconsole=4.5.1=py_0
  - r=3.6.0=r36_0
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.0
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-blob=1.1.1
  - r-boot=1.3_20
  - r-broom=0.5.2
  - r-callr=3.2.0
  - r-caret=6.0_83
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=3.3
  - r-data.table=1.12.2
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.1.0
  - r-essentials=3.6.0=r36_0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-formatr=1.6
  - r-fs=1.2.7
  - r-generics=0.0.2
  - r-ggplot2=3.1.1
  - r-glmnet=2.0_16
  - r-glue=1.3.1
  - r-gower=0.2.0
  - r-gtable=0.3.0
  - r-haven=2.1.0
  - r-hexbin=1.27.2
  - r-highr=0.8
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.5.1
  - r-httr=1.4.0
  - r-ipred=0.9_8
  - r-irdisplay=0.7.0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.22
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lava=1.6.5
  - r-lazyeval=0.2.2
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-memoise=1.1.0
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-modelmetrics=1.2.2
  - r-modelr=0.1.4
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1
  - r-openssl=1.3
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-prodlim=2018.04.18
  - r-progress=1.2.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-quantmod=0.4_14
  - r-r6=2.4.0
  - r-randomforest=4.6_14
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcpproll=0.3.0
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.5
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1
  - r-repr=0.19.2
  - r-reprex=0.2.1
  - r-reshape2=1.4.3
  - r-rlang=0.3.4
  - r-rmarkdown=1.12
  - r-rpart=4.1_15
  - r-rsqlite=2.1.1
  - r-rstudioapi=0.10
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.2
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-timedate=3043.102
  - r-tinytex=0.12
  - r-ttr=0.23_4
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-xts=0.11_2
  - r-yaml=2.2.0
  - r-zoo=1.8_5
  - rpy2=2.9.4
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - simplegeneric=0.8.1=py_1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2=py37_0
  - tzlocal=1.5.1=py_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.7


