source('./utils/aerosol_properties_E3SM.R')


getPointCsv <- function(lat,lon,dirname='./data/'){
        filename <- paste0('surface_chem_E3SM_v0_MOA_',toString(lat),'_',toString(lon),'.csv') #default generated by netcdf_to_csv notebook
        df <- read.csv(paste0(dirname,filename))
        dat <- as.data.frame(t(df[,-1]))
        colnames(dat) <- df$X
        return(dat)
}

calculate_dNdlogDp <- function(N_total, sigma_g, Dp, DpgN) {
  tmp <- -((log(Dp/DpgN))^2) / (2.0*(log(sigma_g))^2)
  dNdlogDp <- (N_total/(2.506628*log(sigma_g)) ) *exp(tmp)*
    log(10) # convert from dN/dlnDp to dN/dlogDp
}

makeBins <- function(){
    nbins <- 150    #number of bins for distribution 
    Dp_min <- 1.e-9 # lower bound of first bin (m), corresponds to 1nm
    Dp_max <- 1.e-5 # upper bound of last bin (m), corresponds to 10 micrometers
    dlogDp_max <- log10(Dp_max/Dp_min)
    dlogDp <- dlogDp_max/nbins
    factor_Dp <- 10.**dlogDp # factor used for calculating bins
    
    Dp_low <- array(0,c(nbins,1))  # lower bound of each bin 
    Dp_up <- array(0,c(nbins,1))   # upper bound of each bin
    Dp_mid <- array(0,c(nbins,1))  # midpoint of each bin
    for(i in 1:nbins){
        Dp_low[i] <- Dp_min*factor_Dp**(i-1) 
        Dp_up[i] <- Dp_min*factor_Dp**(i)
        Dp_mid[i] <- (Dp_low[i]+Dp_up[i])/2.
    }
    return(Dp_mid)
} ##output equivalent to SizeDistFunctions.py


## LOAD DATA
args <- commandArgs(trailingOnly = TRUE)
lat <- args[1]
lon <- args[2]
dirname <- args[3]

dat <- getPointCsv(lat,lon,dirname)

## CALCULATE MOIST AIR DENSITY
# Better would be to use (level pressure difference) / gravity
dat$vapor.pressure <- dat$Q/(dat$Q + 0.622) * dat$PS
 
# Dry air density [kg/m3]
dat$dry.density <- dat$PS / (287.0531 * dat$T)
 
# Moist air density [kg/m3]
dat$moist.density <- (dat$PS - dat$vapor.pressure) / (287.0531 * dat$T) +
dat$vapor.pressure/(461.4964 * dat$T)

# Calculate total mass in each mode

# Interstitial aerosol mass mixing ratio [kg/kg]
mmr_a1 <- dat$mom_a1 + dat$ncl_a1 + dat$pom_a1 + dat$soa_a1 + dat$so4_a1 + dat$dst_a1 + dat$bc_a1
mmr_a2 <- dat$mom_a2 + dat$ncl_a2 + dat$soa_a2 + dat$so4_a2
mmr_a3 <- dat$mom_a3 + dat$ncl_a3 + dat$pom_a3 + dat$soa_a3 + dat$so4_a3 + dat$dst_a3 + dat$bc_a3
mmr_a4 <- dat$mom_a4 + dat$pom_a4 + dat$bc_a4
    
# Cloud-borne aerosol mass mixing ratio [kg/kg]
mmr_c1 <- dat$mom_c1 + dat$ncl_c1 + dat$pom_c1 + dat$soa_c1 + dat$so4_c1 + dat$dst_c1 + dat$bc_c1
mmr_c2 <- dat$mom_c2 + dat$ncl_c2 + dat$soa_c2 + dat$so4_c2
mmr_c3 <- dat$mom_c3 + dat$ncl_c3 + dat$pom_c3 + dat$soa_c3 + dat$so4_c3 + dat$dst_c3 + dat$bc_c3
mmr_c4 <- dat$mom_c4 + dat$pom_c4 + dat$bc_c4

# Calculate volume mixing ratio in each mode [m3/kg]
vol_per_kg_a1 <- (dat$mom_a1/density_mom + dat$ncl_a1/density_ncl + dat$pom_a1/density_pom +
                        dat$soa_a1/density_soa + dat$so4_a1/density_so4 + dat$dst_a1/density_dst +
                        dat$bc_a1/density_bc)
vol_per_kg_a2 <- (dat$mom_a2/density_mom + dat$ncl_a2/density_ncl +
                        dat$soa_a2/density_soa + dat$so4_a2/density_so4)
vol_per_kg_a3 <- (dat$mom_a3/density_mom + dat$ncl_a3/density_ncl + dat$pom_a3/density_pom +
                        dat$soa_a3/density_soa + dat$so4_a3/density_so4 + dat$dst_a3/density_dst + dat$bc_a3/density_bc)
vol_per_kg_a4 <- (dat$mom_a4/density_mom + dat$pom_a4/density_pom + dat$bc_a4/density_bc)
    
# Cloud-borne aerosol volume mixing ratio [m3/kg]
vol_per_kg_c1 <- (dat$mom_c1/density_mom + dat$ncl_c1/density_ncl + dat$pom_c1/density_pom +
                        dat$soa_c1/density_soa + dat$so4_c1/density_so4 + dat$dst_c1/density_dst + dat$bc_c1/density_bc)
vol_per_kg_c2 <- (dat$mom_c2/density_mom + dat$ncl_c2/density_ncl +
                        dat$soa_c2/density_soa + dat$so4_c2/density_so4)
vol_per_kg_c3 <- (dat$mom_c3/density_mom + dat$ncl_c3/density_ncl + dat$pom_c3/density_pom +
                        dat$soa_c3/density_soa + dat$so4_c3/density_so4 + dat$dst_c3/density_dst + dat$bc_c3/density_bc)
vol_per_kg_c4 <- (dat$mom_c4/density_mom + dat$pom_c4/density_pom + dat$bc_c4/density_bc)

# Interstitial
mass_a1 <- mmr_a1*1.e12*dat$moist.density
mass_a2 <- mmr_a2*1.e12*dat$moist.density
mass_a3 <- mmr_a3*1.e12*dat$moist.density
mass_a4 <- mmr_a4*1.e12*dat$moist.density

# Cloud-borne
mass_c1 <- mmr_c1*1.e12*dat$moist.density
mass_c2 <- mmr_c2*1.e12*dat$moist.density
mass_c3 <- mmr_c3*1.e12*dat$moist.density
mass_c4 <- mmr_c4*1.e12*dat$moist.density

# Convert from [m3/kg] to [m3/m3]
# Convert to (cm^3/mol_air)

# Use moist air density    
mol_air_per_m3 <- dat$moist.density
    
vol_a1 <- vol_per_kg_a1*dat$moist.density
vol_a2 <- vol_per_kg_a2*dat$moist.density
vol_a3 <- vol_per_kg_a3*dat$moist.density
vol_a4 <- vol_per_kg_a4*dat$moist.density

# Convert from [m3/kg] to [m3/m3]
# Convert to (cm^3/mol_air)

# Use moist air density
mol_air_per_m3 <- dat$moist.density

vol_a1 <- vol_per_kg_a1*dat$moist.density
vol_a2 <- vol_per_kg_a2*dat$moist.density
vol_a3 <- vol_per_kg_a3*dat$moist.density
vol_a4 <- vol_per_kg_a4*dat$moist.density

# Convert from [m3/kg] to [m3/m3]
# Convert to (cm^3/mol_air)
vol_c1 <- vol_per_kg_c1*dat$moist.density
vol_c2 <- vol_per_kg_c2*dat$moist.density
vol_c3 <- vol_per_kg_c3*dat$moist.density
vol_c4 <- vol_per_kg_c4*dat$moist.density

# Mode median diameter
# Compare subroutine modal_aero_calcsize_sub() in modal_aero_calcsize.F90
dgn_a1 <- dat$dgnd_a01
dgn_a2 <- dat$dgnd_a02
dgn_a3 <- dat$dgnd_a03
dgn_a4 <- dat$dgnd_a04

# Compute [dry] volume-to-number ratio [cm^3 m^-3]
v2n_a1 <- vol_a1 / dgn_a1
v2n_a2 <- vol_a2 / dgn_a2
v2n_a3 <- vol_a3 / dgn_a3
v2n_a4 <- vol_a4 / dgn_a4


Dp = makeBins()

station.aerosols <- dat


# Initialize empty data frames for station data.
dNdlogDp <- data.frame(stringsAsFactors=FALSE)
station_OMF_dp <- data.frame(stringsAsFactors=FALSE)
station_chemistry_dp <- data.frame(stringsAsFactors=FALSE)

for (i in 1:dim(station.aerosols)[1]) {
    for (phase in c("a", "c")) {
        for (amode in 1:4) {
          # Get aerosol number and mode median diameter at each station;
          # compute number in each bin.  Units: [1/kg]*[kg/m^3]*[m^3/(1e6 cc)] = #/cc.

            assign(paste("bin_num_", phase, amode, sep=""),
                   calculate_dNdlogDp(
                       station.aerosols[[paste("num_", phase, amode, sep="")]][i]*
                       station.aerosols[["moist.density"]][i]*1.e-6,
                       sigma_g[amode], Dp,
                       station.aerosols[[paste("dgnd_a0", amode, sep="")]][i]
                   ))
            
            # Compute volume in each bin.
            assign(paste("bin_vol_", phase, amode, sep=""),
                   get(paste("bin_num_", phase, amode, sep="")) *
                   0.523599 * Dp^3 * 1.e18) # um^3/cc(air)
            
            # Compute volume fraction of marine organics, salt.
            for (species in c("mom", "ncl", "pom", "soa", "so4", "dst", "bc")) {
                assign(paste("bin_", species, "_vol_", phase, amode, sep=""),
                       # Calculate species volume fraction
                       (station.aerosols[[paste(species, "_", phase, amode, sep="")]][i] /
                        get(paste("density_", species, sep=""))) /
                       get(paste("vol_per_kg_", phase, amode, sep=""))[i] *
                       # Multiply by total modal volume projection into bin
                       get(paste("bin_vol_", phase, amode, sep=""))
                      )
                #        assign(paste("bin_", species, "_vol", sep=""),
                #               get(paste("bin_", species, "_vol", sep="")) +
                #                 get(paste("bin_", species, "_vol_", phase, amode, sep="")))
            }
                  
            # compute volume-weighted kappa species contributions
            assign(paste("kappa_marine_", phase, amode, sep=""),
                   (kappa_mom * get(paste("bin_mom_vol_", phase, amode, sep="")) +
                    kappa_ncl * get(paste("bin_ncl_vol_", phase, amode, sep=""))) /
                   get(paste("bin_mom_vol_", phase, amode, sep="")) +
                   get(paste("bin_ncl_vol_", phase, amode, sep="")))                
        } #end mode loop 1
    }#end phase loop 1
    
    # Size-resolved aerosol chemistry
    for (species in c("mom", "ncl", "pom", "soa", "so4", "dst", "bc")) {
        assign(paste("bin_", species, "_vol", sep=""), 0)
        assign(paste("bin_", species, "_mass", sep=""), 0)
        assign(paste("bin_", species, "_num", sep=""), 0)
        for (phase in c("a", "c")) {
            for (amode in 1:4) {
                if (exists(paste("bin_", species, "_vol_", phase, amode , sep=""))) {
                    if (length(get(paste("bin_", species, "_vol_", phase, amode , sep=""))) > 0) {
                        ### Speciated volume distribution
                        #            print(paste("Assigning bin_", species, "_vol_", phase, amode , sep=""))
                        assign(paste("bin_", species, "_vol", sep=""),
                               get(paste("bin_", species, "_vol", sep="")) +
                               get(paste("bin_", species, "_vol_", phase, amode , sep="")) )
                    }
                    ### Speciated number distribution
                    if (any(names(station.aerosols) == paste(species, "_", phase, amode, sep=""))) {
                        assign(paste("bin_", species, "_num", sep=""),
                               get(paste("bin_", species, "_num", sep="")) +
                               get(paste("bin_num_", phase, amode , sep="")) *
                               station.aerosols[[paste(species, "_", phase, amode, sep="")]][i] /
                               get(paste("mmr_", phase, amode, sep=""))[i]
                              )
                    }
                }
            } # End loop amode 2
        } # End loop phase 2
    } # End loop species

  # Total number.
  bin_num <- 0
  bin_vol <- 0
  for (phase in c("a", "c")) {
    for (amode in 1:4) {
      bin_num <- bin_num + get(paste("bin_num_", phase, amode, sep=""))
      bin_vol <- bin_vol + get(paste("bin_vol_", phase, amode, sep=""))
    } # end loop amode
  } # end loop phase
    
      
  # Size-resolved organic mass fraction of sea spray aerosol.
  bin_OMF <- (bin_mom_vol * density_mom) /
    (bin_mom_vol * density_mom + bin_ncl_vol * density_ncl)
    
  # Construct station_OMF_dp data frame, which contains size-resolved
  # kappa and mass fraction, for both MOM and NCl components separately,
  # at each station.
  station_OMF_dp <- rbind.data.frame(station_OMF_dp,
                                     data.frame(
                                       Dp_um=rep(Dp, 2)*1.e6,
                                       month=rownames(station.aerosols)[i],                 
                                       partial_kappa=c(kappa_mom * pmin(bin_mom_vol / (bin_mom_vol + bin_ncl_vol), 1, na.rm=TRUE),
                                                       kappa_ncl * pmin(bin_ncl_vol / (bin_mom_vol + bin_ncl_vol), 1, na.rm=TRUE)),
                                       mass_fraction=c(bin_OMF,
                                                       1-bin_OMF),
                                       type=c(rep("MOM", length(Dp)),
                                              rep("NCl", length(Dp))),
                                       station=rep(paste0("Location: ",toString(lat),', ',toString(lon)),length(Dp))
                                     )
                                    )
                    
    station_chemistry_dp <- rbind.data.frame(station_chemistry_dp,
                                           data.frame(Dp_um=rep(Dp, 7)*1.e6,
                                                      vol=c(bin_mom_vol,
                                                            bin_ncl_vol,
                                                            bin_pom_vol,
                                                            bin_soa_vol,
                                                            bin_so4_vol,
                                                            bin_dst_vol,
                                                            bin_bc_vol),
                                                      vol_frac=c(pmin(bin_mom_vol / bin_vol, 1, na.rm=TRUE),
                                                                 pmin(bin_ncl_vol / bin_vol, 1, na.rm=TRUE),
                                                                 pmin(bin_pom_vol / bin_vol, 1, na.rm=TRUE),
                                                                 pmin(bin_soa_vol / bin_vol, 1, na.rm=TRUE),
                                                                 pmin(bin_so4_vol / bin_vol, 1, na.rm=TRUE),
                                                                 pmin(bin_dst_vol / bin_vol, 1, na.rm=TRUE),
                                                                 pmin(bin_bc_vol  / bin_vol, 1, na.rm=TRUE)),
                                                      partial_kappa=c(kappa_mom * pmin(bin_mom_vol / bin_vol, 1, na.rm=TRUE),
                                                                      kappa_ncl * pmin(bin_ncl_vol / bin_vol, 1, na.rm=TRUE),
                                                                      kappa_pom * pmin(bin_pom_vol / bin_vol, 1, na.rm=TRUE),
                                                                      kappa_soa * pmin(bin_soa_vol / bin_vol, 1, na.rm=TRUE),
                                                                      kappa_so4 * pmin(bin_so4_vol / bin_vol, 1, na.rm=TRUE),
                                                                      kappa_dst * pmin(bin_dst_vol / bin_vol, 1, na.rm=TRUE),
                                                                      kappa_bc  * pmin(bin_bc_vol  / bin_vol, 1, na.rm=TRUE)),
                                                      num=c(bin_mom_num,
                                                            bin_ncl_num,
                                                            bin_pom_num,
                                                            bin_soa_num,
                                                            bin_so4_num,
                                                            bin_dst_num,
                                                            bin_bc_num),
                                                      num_frac=c(pmin(bin_mom_num / bin_num, 1, na.rm=TRUE),
                                                                 pmin(bin_ncl_num / bin_num, 1, na.rm=TRUE),
                                                                 pmin(bin_pom_num / bin_num, 1, na.rm=TRUE),
                                                                 pmin(bin_soa_num / bin_num, 1, na.rm=TRUE),
                                                                 pmin(bin_so4_num / bin_num, 1, na.rm=TRUE),
                                                                 pmin(bin_dst_num / bin_num, 1, na.rm=TRUE),
                                                                 pmin(bin_bc_num  / bin_num, 1, na.rm=TRUE)),
                                                      type=c(rep("mom", length(Dp)),
                                                             rep("ncl", length(Dp)),
                                                             rep("pom", length(Dp)),
                                                             rep("soa", length(Dp)),
                                                             rep("so4", length(Dp)),
                                                             rep("dst", length(Dp)),
                                                             rep("bc" , length(Dp))),
                                                      station=rep(paste0("Location: ",toString(lat),', ',toString(lon)),length(Dp)),
                                                      month=rownames(station.aerosols)[i]
                                                     )
                                             )
    
}#end station/month loop
